# Buổi 03: Luyện tập với Numpy _ Practice at home

## Phân tích và hiển thị dữ liệu

In [1]:
# list range: tạo ra sự khác biệt giữa chuỗi và numpy
v = list(range(1,6))
print(v)
print(2*v)
#

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [2]:
import numpy as np
v = np.arange(1,6)
print(v)
print(v*2)

[1 2 3 4 5]
[ 2  4  6  8 10]

#### Khi khai báo biến là biến Numpy thì Python sẽ hiểu đó không phải chỉ đơn thuần là chuỗi, Numpy có thể cộng trừ nhân chia và có hướng chứ không vô hướng

In [4]:
fruits = ["apple", "banana", "cherry"] #lists []
colors = ("red", "green", "blue") #tuples ()
animals = {'cat', 'dog'} #sets {}
person = {"name" : "Tom", "age" : 20} #dictionaries {}
print(fruits)
print(colors)
print(animals)
print(person)

['apple', 'banana', 'cherry']
('red', 'green', 'blue')
{'dog', 'cat'}
{'name': 'Tom', 'age': 20}

In [12]:

x = [60, 70, 80, 90]
#ĐỐi với dữ liệu dạng chuỗi, có thể lấy dữ liệu theo thứ tự, dạng tuple có thứ tự nên kiểm tra dữ liệu
print('len(x)=',len(x))
#Hàm len: đếm số ký tự có trong chuỗi: chuỗi ở đây có 4 số là 60,70,80,90
print('x[0]=',x[0])
print('x[1]=', x[1])
print('x[-1]=',x[-1])
print('x[1:3]=',x[1:3])
print('x[1:4]=',x[1:4])

len(x)= 4
x[0]= 60
x[1]= 70
x[-1]= 90
x[1:3]= [70, 80]
x[1:4]= [70, 80, 90]

In [16]:
from IPython.display import display
#Display không có sẵn mà phải import từ thư viện của Python vào
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a * b
#Tương tự như việc nhân vector có hướng. Kết quả là 1 vector có hướng khác
print('c = ')
display(c)

c =

array([ 4, 10, 18])

In [18]:
import numpy as np

a = np.zeros((2,2))
display(a)
#Tạo một ma trận vuông 2x2 với tất cả đều bằng 0

b = np.ones((3,2))
display(b)
#Tạo một ma trận 3 hàng, 2 cột với các phần tử đều bằng 1

c = np.full((4,5),7)
display(c)
#Tạo một ma trận 4 hàng 5 cột với các phần tử đều bằng 7

d = np.eye(4)
display(d)
#Tạo một ma trận, ma trận np.eye là ma trận đơn vị với 4 hàng 4 cột, đường chéo ma trận đơn vị luôn bằng 1, các phần tử còn lại sẽ bằng 0

e = np.random.random((2,2))
Tạo một ma trận ngẫu nhiên 2 hàng 2 cột, riên gma

display(e)

array([[0., 0.],
       [0., 0.]])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

array([[0.92551762, 0.49944022],
       [0.31738184, 0.74994794]])

In [3]:

import numpy as np
a = np.arange(15, dtype=float)
display(a)
#np.range có nghĩa là tạo một mảng có 15 phần tử, dtype: xác định kiểu dữ liệu cần yêu cầu. Ở đây float là cần in ra kiểu dữ liệu là số nguyên

a = a.reshape(3,5)
display(a)
#Hàm reset có nghĩa là chuyển đổi, từ mảng thành một ma trận có 3 dòng 5 cột

display(a.shape)
#shape: cho biết kích thước của mảng dữ liệu, ở đây sẽ có kết quả là (3,5)

display(a.ndim)
#ndim: viết tắt của dimension nghĩa là số lượng hướng, ở đây có 2 hướng là dòng và cột

display(a.dtype)
#dtype: trả về kiểu dữ liệu của mảng, có thể là float64 hoặc float32

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

(3, 5)

2

dtype('float64')

In [7]:
import numpy as np
a = np.array([1,2,3,4,5,6])
display(a)

a=a.reshape(2,3)
display(a)

array([1, 2, 3, 4, 5, 6])

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
git push origin gh-pages --force

SyntaxError: invalid syntax (114163457.py, line 1)

In [3]:
import numpy as np
a = np.arange(1, 10).reshape(3,3)
display(a)

display(a[2])
display(a[2].shape)

display(a[2,:])
display(a[2,:].shape)

display(a[2:,:])
display(a[2:,:].shape)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([7, 8, 9])

(3,)

array([7, 8, 9])

(3,)

array([[7, 8, 9]])

(1, 3)

### Pandas

In [4]:
from IPython.display import display
import pandas as pd
a = pd.DataFrame({
        'a': [4,5,6],
        'b': [7,8,9],
        'c': [10,11,12],
    }, index = [1,2,3])
display(a)
display(a.loc[1])

b = pd.DataFrame([
    {'a':4,'b':7,'c':10},
    {'a':5,'b':8,'c':11},
    {'a':6,'b':9,'c':12},
])
display(b)
display(b.loc[1])

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

a     4
b     7
c    10
Name: 1, dtype: int64

   a  b   c
0  4  7  10
1  5  8  11
2  6  9  12

a     5
b     8
c    11
Name: 1, dtype: int64

In [5]:

display(type(a))

pandas.core.frame.DataFrame

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

s = pd.Series([1,3,5,np.nan,6,8])
display(s)

dates = pd.date_range('20181001', periods = 6)
display(dates)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

DatetimeIndex(['2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04',
               '2018-10-05', '2018-10-06'],
              dtype='datetime64[ns]', freq='D')

In [8]:
df = pd.DataFrame(np.random.randn(6,4), columns=['A','B','C','D'], index = dates)
display(df)

display(df.loc['2018-10-03'])
display(df['B'])

                   A         B         C         D
2018-10-01 -1.090329 -0.575163  0.477755 -0.249533
2018-10-02  1.889949  1.763073 -0.624167 -0.638095
2018-10-03  0.491090 -0.213156  0.835394 -0.351031
2018-10-04  0.626860 -0.523591  0.576656 -1.011021
2018-10-05 -0.418815 -0.449220 -0.068250 -1.014114
2018-10-06  0.805125 -1.592702  0.744130 -0.868775

A    0.491090
B   -0.213156
C    0.835394
D   -0.351031
Name: 2018-10-03 00:00:00, dtype: float64

2018-10-01   -0.575163
2018-10-02    1.763073
2018-10-03   -0.213156
2018-10-04   -0.523591
2018-10-05   -0.449220
2018-10-06   -1.592702
Freq: D, Name: B, dtype: float64

In [9]:

df = pd.DataFrame(np.random.randn(3,5), columns=list('ABCDE'), index=['student 1','student 2', 'student 3'])
df

                  A         B         C         D         E
student 1  1.169017 -0.625081  0.961671  0.323665 -0.728074
student 2  0.625219  0.100492 -0.437669 -0.062928 -1.165161
student 3  1.068113 -0.810431 -1.890978  0.818275  0.497982

## Kết thúc